# Generated by Django 4.2.7 on 2023-12-11 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorProfileManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 23, 47, 20, 984687)),
        ),
    ]
