# Generated by Django 4.2.7 on 2023-12-06 07:33

import VendorProfileManagementApp.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorProfileManagementApp', '0002_historicalperformancemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 13, 3, 12, 39826)),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_number',
            field=models.CharField(default=VendorProfileManagementApp.models.generate_unique_number, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
