# Generated by Django 4.2.7 on 2023-12-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorProfileManagementApp', '0003_alter_purchaseordermodel_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 2, 29, 51, 422070)),
        ),
    ]
